from pykafka import KafkaClient, producer
import threading
import datetime as dt
import random
import json

KAFKA_HOST = "localhost:9092"

client = KafkaClient(hosts=KAFKA_HOST)
topic = client.topics[b"raw-weather-reports"]


def generate_random_measurement():
    return random.randint(1, 100)


def generate_random_city():
    return random.choice(["Austin", "San Antonio", "Dallas"])


def generate_random_state():
    return random.choice(["Texas", "Nebraska", "Nevada"])


def generate_random_county():
    return random.choice(["Harris", "Bexar", "McLennan"])


def generate_random_latitude():
    return round(random.uniform(30.0, 33.0), 2)


def generate_random_longitude():
    return round(random.uniform(-99.0, -97.0), 2)

# Create a producer
with topic.get_producer() as producer:
    for i in range(10):
        # make the payload
        json_payload = {
            "time": str(dt.datetime.now()),
            "measurement": generate_random_measurement(),
            "location": generate_random_city(),
            "state": generate_random_state(),
            "county": generate_random_county(),
            "latitude": generate_random_latitude(),
            "longitude": generate_random_longitude(),
            "remarks": f"Generated by Kafka Producer 1 at {dt.datetime.now()}"
        }

        encoded_message = json.dumps(json_payload).encode("utf-8")

        # Specify partition 0, because issues.
        partition_key = b"0"

        producer.produce(encoded_message, partition_key=partition_key)

        print(f"Produced message {i + 1}: {json_payload}")